FROM python:3.11-slim as bot_image

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    openssh-server \
    python3-dev \
    binutils

RUN echo 'root:123' | chpasswd

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config

WORKDIR /app
COPY .env ./ 

COPY requirements.txt ./ 
RUN pip3 install --no-cache-dir -r requirements.txt

COPY bot.py .

EXPOSE 22

CMD service ssh start && python bot.py
